/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVenuesRouteImport } from './routes/_admin.venues'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as AdminTeamRouteImport } from './routes/_admin.team'
import { Route as AdminReportsRouteImport } from './routes/_admin.reports'
import { Route as AdminMessagesRouteImport } from './routes/_admin.messages'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminBookingsRouteImport } from './routes/_admin.bookings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bookings': typeof AdminBookingsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/messages': typeof AdminMessagesRoute
  '/reports': typeof AdminReportsRoute
  '/team': typeof AdminTeamRoute
  '/users': typeof AdminUsersRoute
  '/venues': typeof AdminVenuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bookings': typeof AdminBookingsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/messages': typeof AdminMessagesRoute
  '/reports': typeof AdminReportsRoute
  '/team': typeof AdminTeamRoute
  '/users': typeof AdminUsersRoute
  '/venues': typeof AdminVenuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/bookings': typeof AdminBookingsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/messages': typeof AdminMessagesRoute
  '/_admin/reports': typeof AdminReportsRoute
  '/_admin/team': typeof AdminTeamRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/venues': typeof AdminVenuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bookings'
    | '/dashboard'
    | '/messages'
    | '/reports'
    | '/team'
    | '/users'
    | '/venues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bookings'
    | '/dashboard'
    | '/messages'
    | '/reports'
    | '/team'
    | '/users'
    | '/venues'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/bookings'
    | '/_admin/dashboard'
    | '/_admin/messages'
    | '/_admin/reports'
    | '/_admin/team'
    | '/_admin/users'
    | '/_admin/venues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/venues': {
      id: '/_admin/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/team': {
      id: '/_admin/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reports': {
      id: '/_admin/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/messages': {
      id: '/_admin/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bookings': {
      id: '/_admin/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVenuesRoute: AdminVenuesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
